
name: Auto-generate map

on:
  push:
    paths:
      - '**.gpx'
      - '**/shops.json'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install folium gpxpy

    - name: Generate Maps for All Months
      working-directory: ${{ github.workspace }}
      run: |
        for folder in $(find . -maxdepth 1 -type d -regex './[0-9]{4}-[0-9]{2}'); do
          folder_name=$(basename "$folder")
          echo "🔄 正在產生 $folder_name"
          python scripts/generate_map.py "$folder_name"
        done

    - name: Commit and Push Map
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "auto: 更新地圖" || echo "No changes to commit"
        git pull --rebase
        git push
