name: Auto-generate map

on:
  push:
    branches:
      - '**'
    paths:
      - '2025-05/*.gpx'
      - 'scripts/generate_map.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Generate Map
        run: python scripts/generate_map.py

      - name: Commit and Push Map
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action
