name: Auto-generate map

on:
  push:
    paths:
      - '**.gpx'
      - '.github/workflows/build.yml'
      - 'scripts/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install folium gpxpy

    - name: Generate Map
      run: python scripts/generate_map.py

    - name: Commit and Push Map
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add .
        git commit -m "Auto-generate map"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
